/* Generated By:JavaCC: Do not edit this line. RegexParserTreeConstants.java Version 5.0 */
package regexparser;

public interface RegexParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOP = 2;
  public int JJTTERMINAL = 3;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Op",
    "Terminal",
  };
}
/* JavaCC - OriginalChecksum=e8b383a59275794f330f46fa3d8fd2ce (do not edit this line) */
