/* Generated By:JJTree&JavaCC: Do not edit this line. RegexParserConstants.java */
package regexparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDL = 6;
  /** RegularExpression Id. */
  int OPEN = 7;
  /** RegularExpression Id. */
  int CLOSE = 8;
  /** RegularExpression Id. */
  int STAR = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int EPSILON = 11;
  /** RegularExpression Id. */
  int SYM = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\"!\"",
    "<SYM>",
  };

}
