/* Generated By:JavaCC: Do not edit this line. FileParserTreeConstants.java Version 5.0 */
package fileparser;

public interface FileParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATES = 1;
  public int JJTTRANSITIONS = 2;
  public int JJTVOID = 3;
  public int JJTSTATE = 4;
  public int JJTTRANSITION = 5;


  public String[] jjtNodeName = {
    "Start",
    "States",
    "Transitions",
    "void",
    "State",
    "Transition",
  };
}
/* JavaCC - OriginalChecksum=b8eb3e719b606546716fa9b71b3b07bf (do not edit this line) */
