/* Generated By:JJTree&JavaCC: Do not edit this line. FileParserConstants.java */
package fileparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FileParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGRAPH = 7;
  /** RegularExpression Id. */
  int RANKDIR = 8;
  /** RegularExpression Id. */
  int START = 9;
  /** RegularExpression Id. */
  int SHAPE = 10;
  /** RegularExpression Id. */
  int COLOR = 11;
  /** RegularExpression Id. */
  int FONTCOLOR = 12;
  /** RegularExpression Id. */
  int POINT = 13;
  /** RegularExpression Id. */
  int WHITE = 14;
  /** RegularExpression Id. */
  int BLACK = 15;
  /** RegularExpression Id. */
  int LABEL = 16;
  /** RegularExpression Id. */
  int CIRCLE = 17;
  /** RegularExpression Id. */
  int DOUBLECIRCLE = 18;
  /** RegularExpression Id. */
  int NODE = 19;
  /** RegularExpression Id. */
  int LR = 20;
  /** RegularExpression Id. */
  int OPEN = 21;
  /** RegularExpression Id. */
  int CLOSE = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int ENDSTMT = 24;
  /** RegularExpression Id. */
  int QUOTE = 25;
  /** RegularExpression Id. */
  int ID = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"digraph\"",
    "\"rankdir\"",
    "\"start\"",
    "\"shape\"",
    "\"color\"",
    "\"fontcolor\"",
    "\"point\"",
    "\"white\"",
    "\"black\"",
    "\"label\"",
    "\"circle\"",
    "\"doublecircle\"",
    "\"node\"",
    "\"LR\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\";\"",
    "\"\\\"\"",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"->\"",
  };

}
