/* Generated By:JJTree&JavaCC: Do not edit this line. StmtParserConstants.java */
package stmtparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StmtParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 6;
  /** RegularExpression Id. */
  int CLOSE = 7;
  /** RegularExpression Id. */
  int NEW = 8;
  /** RegularExpression Id. */
  int FROMREGEX = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int REV = 12;
  /** RegularExpression Id. */
  int NOT = 13;
  /** RegularExpression Id. */
  int STAR = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int UN = 16;
  /** RegularExpression Id. */
  int DIF = 17;
  /** RegularExpression Id. */
  int XOR = 18;
  /** RegularExpression Id. */
  int FA = 19;
  /** RegularExpression Id. */
  int TODFA = 20;
  /** RegularExpression Id. */
  int MIN = 21;
  /** RegularExpression Id. */
  int DUMP = 22;
  /** RegularExpression Id. */
  int PRINT = 23;
  /** RegularExpression Id. */
  int DRAW = 24;
  /** RegularExpression Id. */
  int TEST = 25;
  /** RegularExpression Id. */
  int STRINGDELIM = 26;
  /** RegularExpression Id. */
  int SYM = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int END_STMT = 29;
  /** RegularExpression Id. */
  int ENDL = 30;
  /** RegularExpression Id. */
  int OTHER = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\"new\"",
    "\"fromRegex\"",
    "\".\"",
    "\"=\"",
    "\"rev\"",
    "\"not\"",
    "\"star\"",
    "\"int\"",
    "\"+\"",
    "\"-\"",
    "\"xor\"",
    "\"FA\"",
    "\"dfa\"",
    "\"min\"",
    "\"dump\"",
    "\"print\"",
    "\"draw\"",
    "\"test\"",
    "\"\\\"\"",
    "<SYM>",
    "<STRING>",
    "\";\"",
    "\"\\n\"",
    "<OTHER>",
  };

}
