/* Generated By:JavaCC: Do not edit this line. StmtParserTreeConstants.java Version 5.0 */
package stmtparser;

public interface StmtParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTOP = 3;
  public int JJTSTRING = 4;
  public int JJTSYMBOL = 5;
  public int JJTSKIP = 6;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Assign",
    "Op",
    "String",
    "Symbol",
    "skip",
  };
}
/* JavaCC - OriginalChecksum=7d1975469ef242395b2441f928e5da8c (do not edit this line) */
