/* Generated By:JavaCC: Do not edit this line. StmtParserTreeConstants.java Version 5.0 */
package stmtparser;

public interface StmtParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTASSIGN = 2;
  public int JJTOP = 3;
  public int JJTSTRING = 4;
  public int JJTSYMBOL = 5;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Assign",
    "Op",
    "String",
    "Symbol",
  };
}
/* JavaCC - OriginalChecksum=ce898a12bd7e123f7274c74d5bdffd70 (do not edit this line) */
